pipeline {
    agent any
    stages {
        stage('Build with Docker') {
            steps {
                script {
                    sh 'cd ./ecentralized-cicd-platform/containers
                    
                    docker build -t my-app .'
                }
            }
        }
        stage('Run Tests') {
            steps {
                script {
                    sh 'docker run my-app pytest tests/'
                }
            }
        }
    }
}
